[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --noinput && python manage.py create_admin && python manage.py collectstatic --noinput && gunicorn shop_project.wsgi --log-file -"
